story3/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('exp/', views.exp, name = 'exp'),
    path('contact/', views.kontak, name = 'kontak'),
    path('matkul/', views.buatmatkul, name = 'matkul'),
    path('matkul/create', views.buatmatkul, name = 'create'),
    path('matkul/data', views.posmatkul, name = 'data'),
    path('matkul/data/delete/(?<delete_id>[0-9]+)', views.delete, name = 'delete'),
]

story6ppw/urls.py
from django.urls import path

from .import views

app_name = 'story6'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('create/', views.addKegiatan, name = 'addKegiatan'),
    path('join/<int:p_id>', views.joinPeserta, name = 'joinPeserta')
]

website/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story1/', include('homeprofile.urls')),
    path('', include('story3.urls')),
    path('story6/', include('story6ppw.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8ppw.urls')),
    path('story9/login/', include('story9.urls')),
]

story6ppw/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    nama = models.CharField(max_length=50)

    def __str__(self):
         return self.nama

class Peserta(models.Model):
    nama = models.CharField(max_length=50)
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE) 

    def __str__(self):
        return self.nama


#1 kegiatan punya byk orang, 1 org cuma 1 kegiatan

story6ppw/forms.py
from django import forms
from .models import Kegiatan, Peserta

class KegiatanForm(forms.ModelForm):
    class Meta:
        model = Kegiatan 
        fields = ['nama']
        label = {'nama' : 'Activities'}
        widgets = {
            'nama': forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'enter type of activity'
                }
            )
        }

class PesertaForm(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = '__all__'
        # fields = ['nama']
        # label = {'nama' : 'Name'}
        # widgets = {
        #     'nama': forms.TextInput(
        #         attrs={
        #             'class':'form-control',
        #             'placeholder':'enter type of activity'
        #         }
        #     )
        # }

story6ppw/views.py
from django.shortcuts import render, redirect
from .forms import KegiatanForm, PesertaForm
from .models import Kegiatan, Peserta

# Create your views here.
def index(request):
    pos_kegiatan = Kegiatan.objects.all()
    context = {
        'pos':pos_kegiatan
    }
    return render(request, 'index.html', context)

def addKegiatan(request):
    Kegiatan_form = KegiatanForm(request.POST or None)
    if request.method == 'POST':
        if Kegiatan_form.is_valid():
            Kegiatan_form.save()
            return redirect("/story6/")

    context = {
        'data_form' : Kegiatan_form,
    }
    return render(request, 'addK.html', context)

def joinPeserta(request, p_id):
    default = Kegiatan.objects.get(pk = p_id)
    Peserta_form = PesertaForm(request.POST or None, initial={'kegiatan':default})
    if request.method == 'POST':
        if Peserta_form.is_valid():
            Peserta_form.save()
            return redirect("/story6/")

    context = {
        'data_form' : Peserta_form,
    }
    return render(request, 'join.html', context)
   

story6ppw/templates/addK.html
{% extends "base.html" %}
{%load static%}

{% block content %}
   
<section>
    <form method="POST">
        {% csrf_token %}
        <div class="container mt-5 pt-5 mb-5">
            <h3>Create Activities</h3>
            <br>
            {% for form in data_form %}
            <div class="form-group">
                {{form.label}}
                {{form}}
            </div>
            {%endfor%}
            <br>
        <button class="btn btn-danger" type="Submit">Create</button>
    </div>
    </form>
</section>

    {% endblock content %}

     

story6ppw/templates/index.html
{% extends "base.html" %}
{%load static%}

{% block content %}
   
<section>
    <div class="container mt-5 pt-5 mb-5">
        <h3>Activities</h3>
        <div class="card" style="width: 60rem;">
            {%for p in pos%}
            <div class="card-body">
              <h5 class="card-title">{{p.nama}}</h5>
              {%for peserta in p.peserta_set.all%}
              <p class="card-text">{{peserta.nama}}</p>
              {%endfor%}
              <a href="{%url 'story6:joinPeserta' p_id=p.id %}" class="btn btn-danger" >Join</a>
            </div>
            {%endfor%}
          </div>
          <br>
          <a class= "btn btn-danger" href="{%url 'story6:addKegiatan'%}">Add new activity</a>
    </div>
</section>

    {% endblock content %}

     

story6ppw/templates/join.html
{% extends "base.html" %}
{%load static%}

{% block content %}
   
<section>
    <form method="POST">
        {% csrf_token %}
        <div class="container mt-5 pt-5 mb-5">
            <h3>Join this activity</h3>
            <br>
            {% for form in data_form %}
            <div class="form-group">
                {{form.label}}
                {{form}}
            </div>
            {%endfor%}
            <br>
        <button class="btn btn-danger" type="Submit">Join</button>
    </div>
    </form>
</section>

    {% endblock content %}

     