story3/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('exp/', views.exp, name = 'exp'),
    path('contact/', views.kontak, name = 'kontak'),
    path('matkul/', views.buatmatkul, name = 'matkul'),
    path('matkul/create', views.buatmatkul, name = 'create'),
    path('matkul/data', views.posmatkul, name = 'data'),
    path('matkul/data/delete/(?<delete_id>[0-9]+)', views.delete, name = 'delete'),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'
urlpatterns = [
    path('', views.loginUser, name = 'loginUser'),
    path('logout/', views.logoutUser, name='logoutUser'),
    path('register/', views.register, name = 'register'),
    path('halo/',views.halo, name='halo'),
]

website/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story1/', include('homeprofile.urls')),
    path('', include('story3.urls')),
    path('story6/', include('story6ppw.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8ppw.urls')),
    path('story9/login/', include('story9.urls')),
]

templates/snippets/footer.html
{%load static%}
<footer style="background-color: #eeb2b2;">
  <div class="row">
      <div class="col text-center ">
        <p>Copyright &copy; 2020 Etya Resa Fatma</p>
      </div>
    </div>
</footer>

templates/snippets/navbar.html
{%load static%}
<nav class="navbar fixed-top navbar-expand-lg navbar-light" style="background-color: #F5B5B4;">
    <div class="container">
      <a class="navbar-brand" href="#">Etya Resa</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/exp">Experience</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Courses
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="/matkul">Create</a>
              <a class="dropdown-item" href="/matkul/data">List</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Story
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="/story1">Story1</a>
              <a class="dropdown-item" href="/story6">Story6</a>
              <a class="dropdown-item" href="/story7">Story7</a>
              <a class="dropdown-item" href="/story8">Story8</a>
              <a class="dropdown-item" href="/story9/login">Story9</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/contact">Contact</a>
          </li>

          {% if user.is_authenticated %}
          <li class="nav-item">
          <a href="{% url 'story9:logoutUser' %}" class="nav-link">Logout</a>
          </li>
          <li class="nav-item">
            <a href="/story9/login/halo" class="nav-link">{{user.username}}</a>
          </li>
          {%endif%}
          
      </div>
    </div>
  </nav>

templates/snippets/script.html
{% load static%}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"crossorigin="anonymous"></script> 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src= "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"> </script>
<script src= "https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"> </script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
<script src="{% static 'js/accordion.js' %}"></script>
<script src="{% static 'js/books.js' %}"></script>

templates/snippets/style.html
  {% load static%}
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/style7.css' %}">
  <link rel="stylesheet" href="{% static 'css/story9.css' %}">