story3/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('exp/', views.exp, name = 'exp'),
    path('contact/', views.kontak, name = 'kontak'),
    path('matkul/', views.buatmatkul, name = 'matkul'),
    path('matkul/create', views.buatmatkul, name = 'create'),
    path('matkul/data', views.posmatkul, name = 'data'),
    path('matkul/data/delete/(?<delete_id>[0-9]+)', views.delete, name = 'delete'),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'
urlpatterns = [
    path('', views.loginUser, name = 'loginUser'),
    path('logout/', views.logoutUser, name='logoutUser'),
    path('register/', views.register, name = 'register'),
    path('halo/',views.halo, name='halo'),
]

website/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story1/', include('homeprofile.urls')),
    path('', include('story3.urls')),
    path('story6/', include('story6ppw.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8ppw.urls')),
    path('story9/login/', include('story9.urls')),
]

story9/models.py
from django.db import models

# Create your models here.

story9/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreatUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email' , 'password1', 'password2']

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from .forms import CreatUserForm
from django.contrib import messages

def register(request):
    form = CreatUserForm()
    if request.method == 'POST':
        form = CreatUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('story9:loginUser')
    context ={'form':form}
    return render(request, 'register.html', context)

def loginUser(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('story9:halo')
    return render(request, 'login.html')

def logoutUser(request):
    logout(request)
    return redirect('story9:loginUser')

def halo(request):
    return render(request, 'halo.html')

story9/templates/halo.html
{% extends "base.html" %}
{%load static%}

{% block content %}

<section>
  <div class="container">
    <h1 style="position: relative; text-align: center; padding-top: 50px;">Hello {{ user.username}} !! </h1>
    <img src="{% static 'wfh_7.svg' %}" style="width: 70%; margin-left: 150px;">
  </div>
</section>

{% endblock content %}

story9/templates/login.html
{% extends "base.html" %}
{%load static%}

{% block content %}

<section>
  <div class="container">
    <div class="d-flex justify-content-center h-100 " style="padding-top: 50px">
      <div class="user_card">

        <div class="d-flex justify-content-center">
          <h3 id="form-title">LOGIN</h3>
        </div>

        <div class="d-flex justify-content-center form_container">
          <form method="POST" action="">
            {%csrf_token%}
              
            <div class="input-group mb-3">
              <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-user"></i></span>
              </div>
              <input type="text" name="username" placeholder="Username..." class="form-control">
            </div>

            <div class="input-group mb-2">
              <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-key"></i></span>
              </div>
                <input type="password" name="password" placeholder="Password..." class="form-control" >
            </div>

            {% for message in messages %}
            {% if message.tags == 'success' %}
              <div style="color:black;" role="alert">
                {{ message }}
              </div>
            {% endif %}
            {% if message.tags == 'error' %}
              <div style="color:black;;" role="alert">
                {{ message }}
              </div>
            {% endif %}
            {% endfor %}
  
            <div class="d-flex justify-content-center mt-3 login_container">
              <input class="btn login_btn" type="submit" value="Login">
            </div>
          </form>
        </div>
      
        <div class="mt-4">
          <div class="d-flex justify-content-center links">
            Don't have an account? <a href="{% url 'story9:register'%}" class="ml-2" style="color: white;">Sign Up</a>
          </div>
        </div>

      </div>
    </div>
  </div>
</section>

{% endblock content %}

story9/templates/register.html
{% extends "base.html" %}
{%load static%}

{% block content %}

<section>
<div class="container">
    <div class="d-flex justify-content-center h-100" style="padding-top: 50px">
		<div class="user_card">
			<div class="d-flex justify-content-center">
				<h3 id="form-title">REGISTER ACCOUNT</h3>
			</div>		
			
			<div class="d-flex justify-content-center form_container">
				<form method="POST" action="">
					{%csrf_token%}
					<div class="input-group mb-2">
						<div class="input-group-append">
							<span class="input-group-text"><i class="fas fa-user"></i></span>
						</div>
						<input type="text" name="username" placeholder="Username" class="form-control">
					</div>
            
					<div class="input-group mb-2">
						<div class="input-group-append">
							<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
						</div>
						<input type="email" name="email" placeholder="Email" class="form-control">
					</div>
            
					<div class="input-group mb-2">
						<div class="input-group-append">
							<span class="input-group-text"><i class="fas fa-key"></i></span>
						</div>
						<input type="password" name="password1" placeholder="Password" class="form-control">
					</div>
            
					<div class="input-group mb-2">
						<div class="input-group-append">
							<span class="input-group-text"><i class="fas fa-key"></i></span>
						</div>
						<input type="password" name="password2" placeholder="Confirm password" class="form-control">
					</div>
            
					<div style="color:black;" role="alert">
					{{form.username.errors}}
					{{form.email.errors}}
					{{form.password1.errors}}
					{{form.password2.errors}}
					</div>

					<div class="d-flex justify-content-center mt-3 login_container">
						<input class="btn login_btn" type="submit" value="register">
					</div>
				</form>
			</div>
		
			<div class="mt-4">
				<div class="d-flex justify-content-center links">
					Already have an account? <a href="{% url 'story9:loginUser'%}" class="ml-2" style="text-decoration: none; color: rgb(255, 255, 255);">Login</a>
				</div>
			</div>
			</div>
		</div>
	</div>
</div>
</section>
  
{% endblock content %}